### ISSUE TITLE
Add "Open with..." option

### ISSUE THREAD

**Issue by ehassett** [rkttu/WSL-DistroManager#11]
It would be good to have a feature to open a distro with a specific terminal (and set a default terminal) as opposed to only allwoing the default WSL terminal. For instance, I use Hyper with my WSL install and it would be great to be able to open a distro using WSL Distro Manager in Hyper.

**Comment by ehassett** [comment]
Pull Request #12 adds an option to open a distro in Hyper.
Due to the nuanced configurations for other terminals, it may be best to wait to add the option to open in those other terminals until it is requested.
Also, it doesn't appear possible to open multiple distros at once in Hyper by shift-selecting. If it is figured out, this could be added later as well.

**Comment by rkttu** [comment]
I added code to create a shim to make it easy to use the hyper.js terminal, whether it was installed via the Microsoft Store or not. This code can be used in all cases by simply changing the shell property in the hyper.js configuration file. I will close this issue once the feature development is complete.

https://github.com/rkttu/WSL-DistroManager/commit/89944dee582ceb2733980f459f91482816054ddf
