### ISSUE TITLE
Accidentally removes distro registry

### ISSUE THREAD

**Issue by rkttu** [rkttu/WSL-DistroManager#6]
Condition: Installed only single Ubuntu 16.04 distribution
Steps to reproduce: Double click the row to run specific distro
Symptoms: It throws array index overflow error, then accidentally deleted distro registry
Report link: https://www.facebook.com/groups/200708093411111/permalink/1077255282423050/

**Comment by rkttu** [comment]
I cannot reproduce the symptom in Windows 10 1803 (April Update). I will test it against 1709 and lower version of Windows 10.

**Comment by kesuskim** [comment]
- OS Version: Windows 10.0.17134.48
- Pre-condition: WSL was not running while using this program
- Result: Registry related to WSL has been deleted (under \CurrentVersion\Lxss key disappears)

I tried to re-install WSL from Windows Store, but it said 'Already installed' yet cannot start.
![image](https://user-images.githubusercontent.com/7637982/41211307-6936306c-6d71-11e8-947b-354988ae0949.png)

If I click 'execute', error happens;

![image](https://user-images.githubusercontent.com/7637982/41211315-8385fe48-6d71-11e8-97b8-09cd2c1f3202.png)

**Comment by rkttu-devsisters** [comment]
As a result of tracking and guessing various problem phenomena, it is estimated that there is a problem that the registry key may be erased when unloading wslapi.dll to FreeLibrary after an unhandled exception occurs.

**Comment by ghost** [comment]
Related problems
- Disable WSL via appwiz.cpl, then try launch WSL shell with this program causes index zero exception
- During distro installation, try launch WSL shell with this program causes index zero exception

**Comment by rkttu** [comment]
The cause of the problem is probably caused by the registry key being deleted, but it is not known exactly when and how the registry key is removed. As a workaround for this problem, I want to add the ability to back up the LXSS registry key every time it runs and restore it if necessary.

Once this issue is closed, I will add an issue and a branch for the new feature. Thank you for reporting.
